[2024-12-07T15:00:16.664+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T15:00:16.672+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: a3media_schedule_scraper.PushAllInOne scheduled__2024-12-07T07:00:00+00:00 [queued]>
[2024-12-07T15:00:16.676+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: a3media_schedule_scraper.PushAllInOne scheduled__2024-12-07T07:00:00+00:00 [queued]>
[2024-12-07T15:00:16.676+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-07T15:00:16.683+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2024-12-07 07:00:00+00:00
[2024-12-07T15:00:16.687+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2864) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T15:00:16.688+0000] {standard_task_runner.py:72} INFO - Started process 2865 to run task
[2024-12-07T15:00:16.688+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'a3media_schedule_scraper', 'PushAllInOne', 'scheduled__2024-12-07T07:00:00+00:00', '--job-id', '2039', '--raw', '--subdir', 'DAGS_FOLDER/dag_atresmedia.py', '--cfg-path', '/tmp/tmp3y3ghwdh']
[2024-12-07T15:00:16.689+0000] {standard_task_runner.py:105} INFO - Job 2039: Subtask PushAllInOne
[2024-12-07T15:00:16.713+0000] {task_command.py:467} INFO - Running <TaskInstance: a3media_schedule_scraper.PushAllInOne scheduled__2024-12-07T07:00:00+00:00 [running]> on host b605548c7b8b
[2024-12-07T15:00:16.754+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='a3media_schedule_scraper' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-07T07:00:00+00:00'
[2024-12-07T15:00:16.755+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T15:00:19.500+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-07T15:00:19.502+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-07T15:00:19.507+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T15:00:19.507+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=a3media_schedule_scraper, task_id=PushAllInOne, run_id=scheduled__2024-12-07T07:00:00+00:00, execution_date=20241207T070000, start_date=20241207T150016, end_date=20241207T150019
[2024-12-07T15:00:19.547+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-07T15:00:19.556+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T15:00:19.558+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
