[2024-12-23T23:30:07.166+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-23T23:30:07.176+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper.push_all_in_one scheduled__2024-12-23T17:30:00+00:00 [queued]>
[2024-12-23T23:30:07.181+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper.push_all_in_one scheduled__2024-12-23T17:30:00+00:00 [queued]>
[2024-12-23T23:30:07.182+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-23T23:30:07.190+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): push_all_in_one> on 2024-12-23 17:30:00+00:00
[2024-12-23T23:30:07.194+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=11277) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-23T23:30:07.195+0000] {standard_task_runner.py:72} INFO - Started process 11278 to run task
[2024-12-23T23:30:07.196+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telemadrid_schedule_scraper', 'push_all_in_one', 'scheduled__2024-12-23T17:30:00+00:00', '--job-id', '2699', '--raw', '--subdir', 'DAGS_FOLDER/dag_telemadrid.py', '--cfg-path', '/tmp/tmphw546dfy']
[2024-12-23T23:30:07.197+0000] {standard_task_runner.py:105} INFO - Job 2699: Subtask push_all_in_one
[2024-12-23T23:30:07.225+0000] {task_command.py:467} INFO - Running <TaskInstance: telemadrid_schedule_scraper.push_all_in_one scheduled__2024-12-23T17:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-23T23:30:07.276+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telemadrid_schedule_scraper' AIRFLOW_CTX_TASK_ID='push_all_in_one' AIRFLOW_CTX_EXECUTION_DATE='2024-12-23T17:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-23T17:30:00+00:00'
[2024-12-23T23:30:07.277+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-23T23:30:11.685+0000] {logging_mixin.py:190} INFO - Error: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}
[2024-12-23T23:30:11.686+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-23T23:30:11.691+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-23T23:30:11.692+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telemadrid_schedule_scraper, task_id=push_all_in_one, run_id=scheduled__2024-12-23T17:30:00+00:00, execution_date=20241223T173000, start_date=20241223T233007, end_date=20241223T233011
[2024-12-23T23:30:11.741+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-23T23:30:11.750+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-23T23:30:11.751+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
