[2024-12-12T17:46:00.811+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-12T17:46:00.840+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rtve_schedule_scraper.push_all_in_one scheduled__2024-12-12T11:30:00+00:00 [queued]>
[2024-12-12T17:46:00.850+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rtve_schedule_scraper.push_all_in_one scheduled__2024-12-12T11:30:00+00:00 [queued]>
[2024-12-12T17:46:00.850+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2024-12-12T17:46:00.869+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): push_all_in_one> on 2024-12-12 11:30:00+00:00
[2024-12-12T17:46:00.876+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=21902) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-12T17:46:00.878+0000] {standard_task_runner.py:72} INFO - Started process 21903 to run task
[2024-12-12T17:46:00.878+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rtve_schedule_scraper', 'push_all_in_one', 'scheduled__2024-12-12T11:30:00+00:00', '--job-id', '2395', '--raw', '--subdir', 'DAGS_FOLDER/dag_rtve_selenium.py', '--cfg-path', '/tmp/tmpk47bvrdd']
[2024-12-12T17:46:00.880+0000] {standard_task_runner.py:105} INFO - Job 2395: Subtask push_all_in_one
[2024-12-12T17:46:00.924+0000] {task_command.py:467} INFO - Running <TaskInstance: rtve_schedule_scraper.push_all_in_one scheduled__2024-12-12T11:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-12T17:46:01.022+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rtve_schedule_scraper' AIRFLOW_CTX_TASK_ID='push_all_in_one' AIRFLOW_CTX_EXECUTION_DATE='2024-12-12T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-12T11:30:00+00:00'
[2024-12-12T17:46:01.024+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-12T17:46:03.907+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-12T17:46:03.913+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-12T17:46:03.926+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-12T17:46:03.930+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rtve_schedule_scraper, task_id=push_all_in_one, run_id=scheduled__2024-12-12T11:30:00+00:00, execution_date=20241212T113000, start_date=20241212T174600, end_date=20241212T174603
[2024-12-12T17:46:04.061+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-12T17:46:04.096+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-12T17:46:04.138+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
