[2024-12-07T17:30:20.854+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-07T17:30:20.864+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rtve_schedule_scraper.PushAllInOne scheduled__2024-12-07T11:30:00+00:00 [queued]>
[2024-12-07T17:30:20.869+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rtve_schedule_scraper.PushAllInOne scheduled__2024-12-07T11:30:00+00:00 [queued]>
[2024-12-07T17:30:20.869+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-07T17:30:20.878+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2024-12-07 11:30:00+00:00
[2024-12-07T17:30:20.883+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4926) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-07T17:30:20.884+0000] {standard_task_runner.py:72} INFO - Started process 4927 to run task
[2024-12-07T17:30:20.885+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rtve_schedule_scraper', 'PushAllInOne', 'scheduled__2024-12-07T11:30:00+00:00', '--job-id', '2059', '--raw', '--subdir', 'DAGS_FOLDER/dag_rtve_selenium.py', '--cfg-path', '/tmp/tmpe2fc8mnu']
[2024-12-07T17:30:20.886+0000] {standard_task_runner.py:105} INFO - Job 2059: Subtask PushAllInOne
[2024-12-07T17:30:20.912+0000] {task_command.py:467} INFO - Running <TaskInstance: rtve_schedule_scraper.PushAllInOne scheduled__2024-12-07T11:30:00+00:00 [running]> on host b605548c7b8b
[2024-12-07T17:30:20.954+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rtve_schedule_scraper' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2024-12-07T11:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-07T11:30:00+00:00'
[2024-12-07T17:30:20.955+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-07T17:30:23.067+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-07T17:30:23.068+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-07T17:30:23.078+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-07T17:30:23.078+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rtve_schedule_scraper, task_id=PushAllInOne, run_id=scheduled__2024-12-07T11:30:00+00:00, execution_date=20241207T113000, start_date=20241207T173020, end_date=20241207T173023
[2024-12-07T17:30:23.103+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-07T17:30:23.112+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-07T17:30:23.114+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
