[2024-12-06T12:53:44.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T12:53:44.455+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-03-01T12:00:00+00:00 [queued]>
[2024-12-06T12:53:44.461+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-03-01T12:00:00+00:00 [queued]>
[2024-12-06T12:53:44.462+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-06T12:53:44.470+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2024-03-01 12:00:00+00:00
[2024-12-06T12:53:44.477+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=611) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T12:53:44.478+0000] {standard_task_runner.py:72} INFO - Started process 622 to run task
[2024-12-06T12:53:44.478+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telemadrid_schedule_scraper_v2', 'PushAllInOne', 'scheduled__2024-03-01T12:00:00+00:00', '--job-id', '1144', '--raw', '--subdir', 'DAGS_FOLDER/dag_telemadrid_v2.py', '--cfg-path', '/tmp/tmp84spda8w']
[2024-12-06T12:53:44.480+0000] {standard_task_runner.py:105} INFO - Job 1144: Subtask PushAllInOne
[2024-12-06T12:53:44.510+0000] {task_command.py:467} INFO - Running <TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-03-01T12:00:00+00:00 [running]> on host 01ebcafa06b4
[2024-12-06T12:53:44.566+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telemadrid_schedule_scraper_v2' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2024-03-01T12:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-03-01T12:00:00+00:00'
[2024-12-06T12:53:44.567+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T12:53:46.869+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-06T12:53:46.870+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-06T12:53:46.876+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T12:53:46.876+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telemadrid_schedule_scraper_v2, task_id=PushAllInOne, run_id=scheduled__2024-03-01T12:00:00+00:00, execution_date=20240301T120000, start_date=20241206T125344, end_date=20241206T125346
[2024-12-06T12:53:46.897+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T12:53:46.908+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T12:53:46.910+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
