[2024-12-06T11:31:51.879+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T11:31:51.888+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-02-17T11:32:00+00:00 [queued]>
[2024-12-06T11:31:51.893+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-02-17T11:32:00+00:00 [queued]>
[2024-12-06T11:31:51.893+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-06T11:31:51.901+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2024-02-17 11:32:00+00:00
[2024-12-06T11:31:51.905+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=537) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T11:31:51.906+0000] {standard_task_runner.py:72} INFO - Started process 546 to run task
[2024-12-06T11:31:51.906+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telemadrid_schedule_scraper_v2', 'PushAllInOne', 'scheduled__2024-02-17T11:32:00+00:00', '--job-id', '803', '--raw', '--subdir', 'DAGS_FOLDER/dag_telemadrid_v2.py', '--cfg-path', '/tmp/tmpbevxx4su']
[2024-12-06T11:31:51.908+0000] {standard_task_runner.py:105} INFO - Job 803: Subtask PushAllInOne
[2024-12-06T11:31:51.932+0000] {task_command.py:467} INFO - Running <TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2024-02-17T11:32:00+00:00 [running]> on host d88abb179e8d
[2024-12-06T11:31:51.973+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telemadrid_schedule_scraper_v2' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2024-02-17T11:32:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-02-17T11:32:00+00:00'
[2024-12-06T11:31:51.974+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T11:31:54.712+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-06T11:31:54.713+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-06T11:31:54.719+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T11:31:54.719+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telemadrid_schedule_scraper_v2, task_id=PushAllInOne, run_id=scheduled__2024-02-17T11:32:00+00:00, execution_date=20240217T113200, start_date=20241206T113151, end_date=20241206T113154
[2024-12-06T11:31:54.766+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T11:31:54.775+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T11:31:54.776+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
