[2024-12-06T14:19:58.327+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-06T14:19:58.340+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2016-08-01T13:14:00+00:00 [queued]>
[2024-12-06T14:19:58.347+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2016-08-01T13:14:00+00:00 [queued]>
[2024-12-06T14:19:58.348+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 5
[2024-12-06T14:19:58.359+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): PushAllInOne> on 2016-08-01 13:14:00+00:00
[2024-12-06T14:19:58.363+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2150) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-06T14:19:58.364+0000] {standard_task_runner.py:72} INFO - Started process 2168 to run task
[2024-12-06T14:19:58.365+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'telemadrid_schedule_scraper_v2', 'PushAllInOne', 'scheduled__2016-08-01T13:14:00+00:00', '--job-id', '1864', '--raw', '--subdir', 'DAGS_FOLDER/dag_telemadrid_v2.py', '--cfg-path', '/tmp/tmp_8skdb_x']
[2024-12-06T14:19:58.368+0000] {standard_task_runner.py:105} INFO - Job 1864: Subtask PushAllInOne
[2024-12-06T14:19:58.403+0000] {task_command.py:467} INFO - Running <TaskInstance: telemadrid_schedule_scraper_v2.PushAllInOne scheduled__2016-08-01T13:14:00+00:00 [running]> on host 6b4257da02f0
[2024-12-06T14:19:58.455+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='telemadrid_schedule_scraper_v2' AIRFLOW_CTX_TASK_ID='PushAllInOne' AIRFLOW_CTX_EXECUTION_DATE='2016-08-01T13:14:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2016-08-01T13:14:00+00:00'
[2024-12-06T14:19:58.456+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-06T14:20:01.225+0000] {logging_mixin.py:190} INFO - Archivo actualizado correctamente.
[2024-12-06T14:20:01.226+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-06T14:20:01.232+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-06T14:20:01.233+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=telemadrid_schedule_scraper_v2, task_id=PushAllInOne, run_id=scheduled__2016-08-01T13:14:00+00:00, execution_date=20160801T131400, start_date=20241206T141958, end_date=20241206T142001
[2024-12-06T14:20:01.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-06T14:20:01.273+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-06T14:20:01.274+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
