[2024-12-05T00:39:59.358+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T00:39:59.369+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: rtve_canarias_schedule_scraper.push_all_in_one_task manual__2024-12-05T00:39:43.716039+00:00 [queued]>
[2024-12-05T00:39:59.375+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: rtve_canarias_schedule_scraper.push_all_in_one_task manual__2024-12-05T00:39:43.716039+00:00 [queued]>
[2024-12-05T00:39:59.375+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-05T00:39:59.384+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): push_all_in_one_task> on 2024-12-05 00:39:43.716039+00:00
[2024-12-05T00:39:59.388+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=150) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-05T00:39:59.389+0000] {standard_task_runner.py:72} INFO - Started process 151 to run task
[2024-12-05T00:39:59.389+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'rtve_canarias_schedule_scraper', 'push_all_in_one_task', 'manual__2024-12-05T00:39:43.716039+00:00', '--job-id', '569', '--raw', '--subdir', 'DAGS_FOLDER/dag_rtve_canarias_selenium.py', '--cfg-path', '/tmp/tmpzck21imw']
[2024-12-05T00:39:59.390+0000] {standard_task_runner.py:105} INFO - Job 569: Subtask push_all_in_one_task
[2024-12-05T00:39:59.419+0000] {task_command.py:467} INFO - Running <TaskInstance: rtve_canarias_schedule_scraper.push_all_in_one_task manual__2024-12-05T00:39:43.716039+00:00 [running]> on host d88abb179e8d
[2024-12-05T00:39:59.467+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='rtve_canarias_schedule_scraper' AIRFLOW_CTX_TASK_ID='push_all_in_one_task' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T00:39:43.716039+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T00:39:43.716039+00:00'
[2024-12-05T00:39:59.468+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T00:40:03.751+0000] {logging_mixin.py:190} INFO - Error: 422 {"message": "Invalid request.\n\n\"sha\" wasn't supplied.", "documentation_url": "https://docs.github.com/rest/repos/contents#create-or-update-file-contents", "status": "422"}
[2024-12-05T00:40:03.753+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-05T00:40:03.760+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T00:40:03.761+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=rtve_canarias_schedule_scraper, task_id=push_all_in_one_task, run_id=manual__2024-12-05T00:39:43.716039+00:00, execution_date=20241205T003943, start_date=20241205T003959, end_date=20241205T004003
[2024-12-05T00:40:03.774+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T00:40:03.784+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T00:40:03.785+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
